rvm:
- 2.2
before_install:
- openssl aes-256-cbc -K $encrypted_1b10c4157ce4_key -iv $encrypted_1b10c4157ce4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "Travis Bot"
- git config --global user.email academic532@outlook.com
- cd ~
- git clone --depth=50 --branch=dev git@github.com:academic532/academic532.github.io.git
  build_dir
- cd build_dir
- git checkout -b master
- gem install github-pages
- npm install gitbook-cli -g
script:
- bash -x ./compile.sh
after_success:
- git add --all
- git commit -m":black_nib:Updated By Travis"
- git push -u origin HEAD:master --force
branches:
  only:
  - dev
